pipeline:
  build:
    image: node:6
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: amoussard/app-test
    tags: [ latest ]
    username: amoussard
    password: moabistudio